
#define COLORDEPTH 4 
#define IMGWIDTH 1024
#define IMGHEIGHT 1024
#define MAPWIDTH 256
#define MAPHEIGHT 256
#define DISPLAYSTRINGSIZE 512
#define MENUBUFLEN 120
#define MAXSUBNETS 1024
#define BLOCKWIDTH IMGWIDTH/MAPWIDTH
#define BLOCKHEIGHT IMGHEIGHT/MAPHEIGHT
